### PR TITLE
Added remove function

### PR DESCRIPTION
**Pull request by RossComputerGuy**
Adds a remove function for the service providers, useful for manual removal.

### CODE REVIEW

**Comment by andersevenrud** [comment]
This seems to remove a registered service (contract), not a service provider in its entirety, so I'm not sure what this solves.  Could you elaborate on the "useful" part of your description ?

**Comment by RossComputerGuy** [comment]
https://github.com/emberliteOS/osjs-client/blob/master/src/providers/core.js#L143 I use it in my OS's `destroyUserProviders` function. The idea is that the `CoreServiceProvider` is always running but when the user is logged in then the services for the user is loaded in.

**Comment by andersevenrud** [comment]
I recommend that you use the internal mechanics for this instead of making your own logic around it.

If you split up the provision there's an option for you that makes it behave like you described:

```
// Load all core services upon initialization
osjs.register(CoreServiceProvider, {
  before: true
});

// Load extra services when user has logged in
osjs.register(UserServiceProvider);
```

**Comment by andersevenrud** [comment]
Another thing by making modifying the registered contracts like this is that you have to introduce a state into `provides()` as well in order for this to "tell the truth". But by doing this it's possible to break the dependency chain.

So I'm not sure if introducing something like this feasible, especially since there's already a built-in way to solve this very specific issue.

I'll keep this open for another 24hrs or something while I give it another think.

**Comment by andersevenrud** [comment]
For the reasons previously stated, I've decided not to merge this.

**Pull request closed without merging**
